services:
  # Backend Node.js/Express
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: taw-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
    ports:
      - "3000:3000"
    volumes:
      - ./backend/package.json:/app/package.json:ro
      - ./backend/package-lock.json:/app/package-lock.json:ro
      - ./backend/src:/app/src:ro
      - backend_node_modules:/app/node_modules
    networks:
      - taw-network
    develop:
      watch:
        - action: sync
          path: frontend/src
          target: /app/src
        - action: rebuild
          path: ./backend/package*.json

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: taw-frontend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/angular.json:/app/angular.json:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/package-lock.json:/app/package-lock.json:ro   # se esiste
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - taw-network
    develop:
      watch:
        - action: sync
          path: frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package*.json

# Volumi persistenti
volumes:
  backend_node_modules:
    name: taw_backend_node_modules
  frontend_node_modules:
    name: taw_frontend_node_modules

# Rete personalizzata
networks:
  taw-network:
    name: taw-network
    driver: bridge
