services:
  # Database MongoDB
  mongodb:
    image: mongo:7.0
    container_name: taw-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-taw_flights}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - taw-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Node.js/Express
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: taw-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/${MONGO_DATABASE:-taw_flights}?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
    ports:
      - "3000:3000"
    volumes:
      - ./backend/package.json:/app/package.json:ro
      - ./backend/package-lock.json:/app/package-lock.json:ro
      - ./backend/src:/app/src:ro
      - backend_node_modules:/app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - taw-network
    develop:
      watch:
        - action: sync
          path: frontend/src
          target: /app/src
        - action: rebuild
          path: ./backend/package*.json

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: taw-frontend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/angular.json:/app/angular.json:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/package-lock.json:/app/package-lock.json:ro   # se esiste
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - taw-network
    develop:
      watch:
        - action: sync
          path: frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package*.json

# Volumi persistenti
volumes:
  mongodb_data:
    name: taw_mongodb_data
  mongodb_config:
    name: taw_mongodb_config
  backend_node_modules:
    name: taw_backend_node_modules
  frontend_node_modules:
    name: taw_frontend_node_modules

# Rete personalizzata
networks:
  taw-network:
    name: taw-network
    driver: bridge
