services:
  # Database PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: taw-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: taw_flights
      POSTGRES_USER: taw_user
      POSTGRES_PASSWORD: taw_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres-init:/docker-entrypoint-initdb.d:ro
    networks:
      - taw-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taw_user -d taw_flights"]
      interval: 30s
      timeout: 10s
      retries: 5
    profiles:
      - local

  # Backend Node.js/Express API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: taw-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      # Impostato per Neon di default (sslmode=require). Per usare il DB locale commentare questa riga e scommentare quella sotto.
      - DATABASE_URL=${DATABASE_URL:-postgresql://neondb_owner:npg_VATdkwzO94Wr@ep-holy-water-a2lusn2u-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
      # - DATABASE_URL=postgresql://taw_user:taw_password@database:5432/taw_flights
      - DB_SSL=true
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=secureTemporaryPwd
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend/package.json:/app/package.json:ro
      - ./backend/package-lock.json:/app/package-lock.json:ro
      - ./backend/src:/app/src:ro
      - backend_node_modules:/app/node_modules
      - ./database/postgres-init:/app/database-init:ro
    networks:
      - taw-network
    develop:
      watch:
        - action: sync
          path: backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/package*.json

  # Frontend Angular with Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: taw-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - taw-network
    depends_on:
      - backend

# Volumi persistenti
volumes:
  backend_node_modules:
    name: taw_backend_node_modules
  postgres_data:
    name: taw_postgres_data

# Rete personalizzata
networks:
  taw-network:
    name: taw-network
    driver: bridge
